# Generated by Django 4.1.4 on 2023-01-18 01:11

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_remove_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cpf',
            field=models.IntegerField(max_length=14, unique=True, validators=[account.models.User.validate_cpf]),
        ),
    ]
