# Generated by Django 4.1.4 on 2022-12-28 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Allocation',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='dt_created', null=True, verbose_name='Created at')),
                ('modified_at', models.DateTimeField(auto_now=True, db_column='dt_modified', null=True, verbose_name='Modified at')),
                ('is_active', models.BooleanField(db_column='cs_active', default=True, verbose_name='Active')),
                ('start_date', models.DateField(db_column='dt_start_date', verbose_name='Start Date')),
                ('leave_date', models.DateField(blank=True, db_column='dt_leave_date', null=True, verbose_name='Leave Date')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Code',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='dt_created', null=True, verbose_name='Created at')),
                ('modified_at', models.DateTimeField(auto_now=True, db_column='dt_modified', null=True, verbose_name='Modified at')),
                ('is_active', models.BooleanField(db_column='cs_active', default=True, verbose_name='Active')),
                ('code', models.CharField(db_column='tx_code', max_length=80, verbose_name='Code')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Departament',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='dt_created', null=True, verbose_name='Created at')),
                ('modified_at', models.DateTimeField(auto_now=True, db_column='dt_modified', null=True, verbose_name='Modified at')),
                ('is_active', models.BooleanField(db_column='cs_active', default=True, verbose_name='Active')),
                ('departament_name', models.CharField(db_column='tx_departament_name', max_length=80, verbose_name='Departament Name')),
                ('description', models.CharField(blank=True, db_column='description', max_length=200, null=True, verbose_name='Departament Description')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EmploymentBond',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='dt_created', null=True, verbose_name='Created at')),
                ('modified_at', models.DateTimeField(auto_now=True, db_column='dt_modified', null=True, verbose_name='Modified at')),
                ('is_active', models.BooleanField(db_column='cs_active', default=True, verbose_name='Active')),
                ('type', models.CharField(choices=[('C', 'CLT'), ('P', 'PJ'), ('T', 'Trainee')], db_column='cs_type', max_length=200, verbose_name='Type of Employment Bond')),
                ('description', models.CharField(blank=True, db_column='tx_description', max_length=80, null=True, verbose_name='Description')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='dt_created', null=True, verbose_name='Created at')),
                ('modified_at', models.DateTimeField(auto_now=True, db_column='dt_modified', null=True, verbose_name='Modified at')),
                ('is_active', models.BooleanField(db_column='cs_active', default=True, verbose_name='Active')),
                ('date_clock_register', models.DateField(db_column='dt_clock_register', verbose_name='Date of clock Register')),
                ('hour_clock_register', models.TimeField(db_column='tm_clock_register', verbose_name='Time of clock Register')),
                ('type_clock_register', models.CharField(choices=[('E', 'Entrada'), ('S', 'Saída')], db_column='cs_type_clock_register', max_length=1, verbose_name='Type of Clock Register')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='dt_created', null=True, verbose_name='Created at')),
                ('modified_at', models.DateTimeField(auto_now=True, db_column='dt_modified', null=True, verbose_name='Modified at')),
                ('is_active', models.BooleanField(db_column='cs_active', default=True, verbose_name='Active')),
                ('role_name', models.CharField(db_column='tx_role_name', max_length=80, verbose_name='Role Name')),
                ('salary', models.FloatField(db_column='nb_salary', verbose_name='Salary')),
                ('scholarity', models.CharField(choices=[('MI', 'Ensino Médio Incompleto'), ('MC', 'Ensino Médio Completo'), ('SI', 'Superior Incompleto'), ('SC', 'Superior Completo'), ('M', 'Mestrado'), ('D', 'Doutorado')], db_column='cs_scholarity', max_length=2, verbose_name='Scholarity')),
                ('graduation', models.CharField(blank=True, db_column='tx_graduation', max_length=80, null=True, verbose_name='Graduation')),
                ('role_description', models.TextField(db_column='tx_role_desc', verbose_name='Role Description')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RelationAllocationFunction',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='dt_created', null=True, verbose_name='Created at')),
                ('modified_at', models.DateTimeField(auto_now=True, db_column='dt_modified', null=True, verbose_name='Modified at')),
                ('is_active', models.BooleanField(db_column='cs_active', default=True, verbose_name='Active')),
                ('allocation', models.ForeignKey(db_column='id_allocation', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.allocation', verbose_name='Allocation')),
                ('role', models.ForeignKey(db_column='id_role', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.role', verbose_name='Role')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='dt_created', null=True, verbose_name='Created at')),
                ('modified_at', models.DateTimeField(auto_now=True, db_column='dt_modified', null=True, verbose_name='Modified at')),
                ('is_active', models.BooleanField(db_column='cs_active', default=True, verbose_name='Active')),
                ('name', models.CharField(db_column='tx_name', max_length=80, verbose_name='Name')),
                ('register_number', models.CharField(db_column='tx_register_number', max_length=5, verbose_name='Register Number')),
                ('birth_date', models.DateField(db_column='dt_birth_date', verbose_name='BirthDate')),
                ('admission_date', models.DateField(db_column='dt_admission_date', verbose_name='Admission Date')),
                ('address', models.CharField(db_column='tx_address', max_length=80, verbose_name='Adress')),
                ('neighborhood', models.CharField(db_column='tx_neighborhood', max_length=80, verbose_name='Neighborhood')),
                ('city', models.CharField(db_column='tx_city', max_length=80, verbose_name='City')),
                ('post_code', models.CharField(db_column='tx_post_code', max_length=15, verbose_name='Post Code')),
                ('state', models.CharField(db_column='tx_state', max_length=2, verbose_name='State')),
                ('phone', models.IntegerField(db_column='nb_phone', verbose_name='Phone')),
                ('email', models.EmailField(db_column='tx_email', max_length=80, verbose_name='Email')),
                ('bond', models.ForeignKey(db_column='id_bond', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.employmentbond', verbose_name='Employee Bond')),
                ('role', models.ForeignKey(db_column='id_role', on_delete=django.db.models.deletion.CASCADE, to='core.role', verbose_name='Role')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='dt_created', null=True, verbose_name='Created at')),
                ('modified_at', models.DateTimeField(auto_now=True, db_column='dt_modified', null=True, verbose_name='Modified at')),
                ('is_active', models.BooleanField(db_column='cs_active', default=True, verbose_name='Active')),
                ('file_name', models.CharField(blank=True, db_column='tx_file_name', max_length=80, null=True, verbose_name='File Name')),
                ('employee', models.ForeignKey(blank=True, db_column='id_employee', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.employee', verbose_name='Employee')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='allocation',
            name='departament',
            field=models.ForeignKey(db_column='id_departament', on_delete=django.db.models.deletion.CASCADE, to='core.departament', verbose_name='Departament'),
        ),
        migrations.AddField(
            model_name='allocation',
            name='employee',
            field=models.ForeignKey(db_column='id_employee', on_delete=django.db.models.deletion.CASCADE, to='core.employee', verbose_name='Employee'),
        ),
    ]
