# Generated by Django 4.1.4 on 2023-01-24 17:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Allocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('leave_date', models.DateField(blank=True, null=True, verbose_name='Leave Date')),
            ],
            options={
                'db_table': 'employees_allocations',
            },
        ),
        migrations.CreateModel(
            name='Departament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departament_name', models.CharField(max_length=80, verbose_name='Departament Name')),
                ('description', models.CharField(blank=True, max_length=200, null=True, verbose_name='Departament Description')),
            ],
            options={
                'db_table': 'tb_departaments',
            },
        ),
        migrations.CreateModel(
            name='EmploymentAssociation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('C', 'CLT'), ('P', 'PJ'), ('O', 'Tercerizado'), ('E', 'Estágio')], max_length=200, verbose_name='Type of Employment Bond')),
                ('description', models.CharField(blank=True, max_length=80, null=True, verbose_name='Description')),
            ],
            options={
                'db_table': 'tb_employment_associations',
            },
        ),
        migrations.CreateModel(
            name='GenerateQrCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qr_code', models.CharField(max_length=80, verbose_name='Code')),
            ],
            options={
                'db_table': 'tb_qrcode',
            },
        ),
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time_register', models.DateTimeField(verbose_name='Date of clock Register')),
                ('type_clock_register', models.CharField(choices=[('E', 'Entrada'), ('S', 'Saída')], max_length=1, verbose_name='Type of Clock Register')),
            ],
            options={
                'db_table': 'tb_registers',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(max_length=80, verbose_name='Role Name')),
                ('salary', models.FloatField(verbose_name='Salary')),
                ('scholarity', models.CharField(choices=[('MI', 'Ensino Médio Incompleto'), ('MC', 'Ensino Médio Completo'), ('SI', 'Superior Incompleto'), ('SC', 'Superior Completo'), ('M', 'Mestrado'), ('D', 'Doutorado')], max_length=2, verbose_name='Scholarity')),
                ('graduation', models.CharField(blank=True, max_length=80, null=True, verbose_name='Graduation')),
                ('role_description', models.TextField(verbose_name='Role Description')),
            ],
            options={
                'db_table': 'tb_roles',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(blank=True, db_column='tx_file_name', max_length=80, null=True, verbose_name='File Name')),
                ('id_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_doc', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tb_document',
            },
        ),
        migrations.CreateModel(
            name='AllocationRoles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allocation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='allocation_related', to='core.allocation')),
                ('id_role', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='role_related', to='core.role')),
            ],
            options={
                'db_table': 'tb_allocation-roles',
            },
        ),
        migrations.AddField(
            model_name='allocation',
            name='id_departament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocation_departament', to='core.departament', verbose_name='Departament'),
        ),
        migrations.AddField(
            model_name='allocation',
            name='id_employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_allocated', to=settings.AUTH_USER_MODEL),
        ),
    ]
