# Generated by Django 4.1.4 on 2023-01-17 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='register_number',
            field=models.CharField(default=69130, max_length=5, verbose_name='Register Number'),
        ),
    ]
